name: 'Build Debian Packages'
description: 'Build both halos and halos-marine bridge metapackages'
runs:
  using: 'composite'
  steps:
    - name: Install build dependencies
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y dpkg-dev debhelper build-essential

    - name: Build halos package
      shell: bash
      run: |
        cd halos
        dpkg-buildpackage -b -uc -us
        mv ../*.deb ../halos/ 2>/dev/null || true

    - name: Build halos-marine package
      shell: bash
      run: |
        cd halos-marine
        dpkg-buildpackage -b -uc -us
        mv ../*.deb ../halos-marine/ 2>/dev/null || true

    - name: Move packages to root
      shell: bash
      run: |
        mv halos/*.deb ./ 2>/dev/null || true
        mv halos-marine/*.deb ./ 2>/dev/null || true
        echo "Built packages:"
        ls -lh *.deb
